### ISSUE TITLE
Missing custom fields

### ISSUE THREAD

**Issue by mikey186** [projectfork/Projectfork#710] opened 2013-08-05 17:04 UTC
I really love the new Projectfork extention. It really change the origional design to the Bootstrap design in which I really really like. And it has almost everything I need.

But one Con I like to put out is that, there is NO custom fields! Most of every project has got to have custom fields (like dropdowns, lists, radio buttons, etc). For example, If one project needs a custom field (like what choices you have), I would need a custom field for that choice. Hope to add that feature in a future version, I be a lot happier.

**Comment by eaxs** [comment] 2015-04-01 17:06
Closing as duplicate of #693

**Closed by eaxs** 2015-04-01 17:06 UTC
Labels: feature
