### ISSUE TITLE
Add Project details fields?

### ISSUE THREAD

**Issue by bokigto** [projectfork/Projectfork#1565] opened 2015-03-16 16:55 UTC
How would one add a few more project details fields?
Can somebody give me an overview?
I guess a good start would be here: /administrator/components/com_pfprojects/models/forms
https://github.com/projectfork/Projectfork/blob/dev/source/components/com_pfprojects/admin/models/forms/project.xml#L101

**Comment by eaxs** [comment] 2015-03-17 14:02
There is currently no way of adding those dynamically through the UI. So yes, you'd have to add them to the form manually. However one downside is that each time you update Projectfork, your changes are reset as the files are replaced with their original.

**Comment by eaxs** [comment] 2015-04-01 17:07
Closing as duplicate of #693

**Closed by eaxs** 2015-04-01 17:07 UTC
Labels: feature
