### ISSUE TITLE
Company Closed Out.

### ISSUE THREAD

**Issue by jrnegronvidal1510** [projectfork/Projectfork#1552] opened 2015-03-03 00:43 UTC
Be Careful. Apparently this company disappeared.

**Comment by eaxs** [comment] 2015-03-04 12:25
Nothing is closing down here. The site is moving, that's all.

**Closed** 2015-03-04 12:26 UTC
Labels: support

**Comment by jrnegronvidal1510** [comment] 2015-03-04 13:01
Well, where I come not do business that way. We plan and execute in a way that is transparent to the client. For us it is important to take the service for which a customer paid us. Otherwise, we would be stealing money to our customer.

I am quite sure that your product is excellent. Unfortunately, I have a problem after doing the installation and have not been supported to solve the problem because there was no one where people are supposed to have.

 

Beyond getting to justify your problem, you should solve the customer's problem.

**Comment by Solinfo** [comment] 2015-03-06 15:19
*lol*

For a closed company, they have full of activity in dev forum and bug fix ;)

Don't stop good job projectfork team

Normand

On 02/03/2015 7:43 PM, jrnegronvidal1510 wrote:
>
> Be Careful. Apparently this company disappeared.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/projectfork/Projectfork/issues/1552>.
>

-- 
Tout en restant Z, il est N* et Q et non pas Im de croire qu'il est C de comprendre en N la partie Q' de R!
(Traduction: Tout en restant relatif, il est naturel et rationnel et non pas imaginaire de croire qu'il est complexe de comprendre en entier la partie irrationnelle des réels!)

Normand Brousseau, B.Sc., M.Sc.
Solinfo enr.
Courriel: mailto:normandb@solinfo.ca
Pages web:
		http://www.solinfo.ca
	   	http://www.ambianceselecte.com


-----------------------------------------------------------------------

AVIS :
Ce message est confidentiel et à l'usage exclusif du destinataire. Toute autre personne est avisée qu'il lui est strictement interdit de le diffuser, distribuer ou reproduire. Si vous avez reçu ce message par erreur, veuillez nous en informer immédiatement par téléphone ou par courriel et effacer toute copie.

NOTICE:
This e-mail is confidential and intended for the exclusive use of the addressee. Any other person is strictly prohibited from disclosing, distributing or reproducing it. If you have received this e-mail by mistake, please notify us immediately by telephone or e-mail and delete all copies.

**Comment by jrnegronvidal1510** [comment] 2015-03-06 15:21
Well, apparently your vision of activity is quite limited.
