### ISSUE TITLE
Add order in project Drag and Drop, similar Drag and Drop in tasks

### ISSUE THREAD

**Issue by pablohenriquem** [projectfork/Projectfork#1574] opened 2015-03-24 20:39 UTC
Hello,

Have possibility Add order in project Drag and Drop similar Drag and Drop in tasks?

Thanks

**Comment by eaxs** [comment] 2015-03-26 17:06
Closing as duplicate of #1539 
Thanks!

**Closed by eaxs** 2015-03-26 17:06 UTC
Labels: feature
