### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by bokigto** [projectfork/Projectfork#1562] opened 2015-03-13 17:48 UTC
We are using Projectfork for managing maintenance issues and repairs at a rental building. 
When initiating a new project or a task, our admins need custom drop down menus to indicate, location of the repair, equipment kind, repair type, etc.  
While labels can be appropriated for this task, they don't seam to do the job. 
Unless you are able to categorize labels. 

Further more it would be nice if one could assign custom fields at the Category level.  
Or assign labels groups at category level. 

Check out the K2 Component (http://getk2.org/) and its Extra Fields feature. 
Think something like that would be nice.

**Comment by eaxs** [comment] 2015-04-01 17:05
Closing as duplicate of #693

**Closed by eaxs** 2015-04-01 17:05 UTC
Labels: feature
