### ISSUE TITLE
Recurring Tasks

### ISSUE THREAD

**Issue by StylizeR** [projectfork/Projectfork#240] opened 2013-01-31 09:59 UTC
ProjectFork 4 doesn't seem to have recurring tasks. This is mandatory for many people.
Could this be implemented? Thnx

**Comment by JurgenG** [comment] 2016-02-17 08:44
This ticket should be closed, it's a duplicate of this one:
https://github.com/projectfork/Projectfork/issues/1526
(actually the other one is the duplicate, but that one has more activity)

**Closed** 2016-03-30 16:59 UTC
Labels: feature
